[package]
name = "llm_readability"
version = "0.0.14"
edition = "2021"
description = "Readability library for LLM's built in Rust"
keywords = ["readability", "clean-html", "safari-reader"]
authors = [
    "j-mendez <jeff@spider.cloud>"
]
repository = "https://github.com/spider-rs/llm-readability"
readme = "README.md"
categories = ["web-programming", "command-line-utilities"]
license = "MIT"
documentation = "https://docs.rs/llm_readability"

[dependencies]
url = "2"
html5ever = "0.39"
markup5ever = "0.39"
tendril = "0.5"
regex = "1"
auto_encoder = "0.2"

[dev-dependencies]
maud = "0.27"
criterion = { version = "0.8", features = ["html_reports"] }

[[bench]]
name = "extraction"
harness = false
